package com.finalproject.hrportal.domain.enums;

public enum InterviewStatus {
    PENDING,REJECTED,SELECTED,INTERVIEW1_CLEARED,INTERVIEW2_CLEARED,HR_CLEARED,
            INTERVIEW1_REJECTED,INTERVIEW2_REJECTED,HR_REJECTED,FORWARDED_TO_NEXT_ROUND,
}
